spring.application.name=insurance-claim-validation

logging.level.com.accenture.insuranceclaimvalidation = INFO

# ======================================================
# GROQ CONFIGURATION
# ======================================================
spring.ai.openai.api-key="your key"

spring.ai.openai.base-url=https://api.groq.com/openai

# Use a model that is available in Groq's OpenAI-compatible API.
spring.ai.openai.chat.options.model=openai/gpt-oss-120b

# ======================================================
# AI CONFIGURATION
# ======================================================
spring.ai.openai.chat.options.temperature=0.2

spring.ai.openai.chat.options.max-tokens=2000

# ======================================================
# MongoDB CONFIGURATION
# ======================================================
spring.data.mongodb.uri=mongodb://localhost:27017/insurance_claim_db
spring.data.mongodb.database=insurance_claim_db